# Generated by Django 5.2.7 on 2025-10-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_departure', models.CharField(max_length=100)),
                ('delivery_City', models.CharField(max_length=100)),
                ('total_Weight', models.IntegerField()),
                ('dimension', models.CharField(max_length=100)),
                ('shipment_Type', models.CharField(max_length=100)),
                ('Urgency_Level', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(max_length=100)),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
